timer_names = ["Abs Trace", 
	"Anasazi: BlockKrylovSchur::Computing Ritz vectors", 
	"Anasazi: BlockKrylovSchur::Computing Schur form",
	"Anasazi: BlockKrylovSchur::Operation Op*x",
	"Anasazi: BlockKrylovSchur::Orthogonalization",
	"Anasazi: BlockKrylovSchur::Sorting Ritz values", 
	"Anasazi: BlockKrylovSchur::Sorting Schur form", 
	"Anasazi: BlockKrylovSchurSolMgr restarting", 
	"Anasazi: BlockKrylovSchurSolMgr::solve()", 
	"Antisymm Frob Norm", 
	"Antisymm Inf Norm", 
	"Avg Nonzeros / Row", 
	"Col Diag Dominance", 
	"Col Variance", 
	"Diadonal Nonzeros", 
	"Diag Variance", 
	"Diagonal Mean", 
	"Diagonal Sign", 
	"Dimension", 
	"Dummy Rows", 
	"Eigen LM", 
	"Eigen LR", 
	"Eigen SM", 
	"Eigen SR",
	"Frob. Norm", 
	"Inf Norm", 
	"Lower Bandwidth", 
	"Max Nonzeros / Row",
	"Min Nonzeros / Row", 
	"Nonzeros", 
	"One Norm", 
	"Row Diag Dominance",
	"Row Variance", 
	"Symm Frob Norm", 
	"Symm Inf Norm", 
	"Symmetry",
	"Trace", 
	"Upper Bandwidth"]

timer_methods = ["MinOverProcs", "MeanOverProcs", "MaxOverProcs", "MeanOverCallCounts"]


for i in timer_names:
	for j in timer_methods:
		print i + " - " + j + ", ",
