cpbsvx(n, nrhs, &a[0][0], lda, ipiv, &b[0][0], ldb, &info)
dgesvx(n, nrhs, &a[0][0], lda, ipiv, &b[0][0], ldb, &info)
cgesvx(n, nrhs, &a[0][0], lda, ipiv, &b[0][0], ldb, &info)
cgbsvx(n, nrhs, &a[0][0], lda, ipiv, &b[0][0], ldb, &info)
sgesvx(n, nrhs, &a[0][0], lda, ipiv, &b[0][0], ldb, &info)
