#
# Script
#
clear

./properties -f /home/javed/Desktop/matrix_properties/matrices/b1_ss.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cage3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/LFAT5_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/LFAT5_M.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/LFAT5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2dal_bci_Aside.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Ragusa18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/LF10_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cage4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Ragusa16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/LF10_M.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/LF10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/d_ss.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Hamrle1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/GD99_b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/football.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Sandi_authors.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/GD01_c.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Trefethen_20b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Trefethen_20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/d_dyn1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2dal_bci_Abottom.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mesh1em6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mesh1e1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mesh1em1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/pores_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bfwb62.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2dal_bci_Atop.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/west0067.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/impcol_b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/impcol_c.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/d_dyn.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/GD97_c.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/west0156.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nos4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cage5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/tub100.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/west0132.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/gre_115.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/olm100.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/odepb400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/impcol_a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/GD01_a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bfwa62.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rw136.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/west0167.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/pivtol.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lns_131.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lnsp_131.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/gre_216a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/SmallW.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/steam3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nos1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/CAG_mat72.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mesh3e1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rotor1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rajat11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/GD00_c.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Trefethen_150.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S10PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M10PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/odepa400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S10PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M10PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/gre_216b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/gre_185.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mesh3em5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/robot.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdb200l.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/impcol_d.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdb200.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Trefethen_200b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Trefethen_200.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/gre_343.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/saylr1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/G11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/G13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/G12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/shl_0.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/GD96_a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/shl_400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/shl_200.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bwm200.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rajat05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/494_bus.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cage6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/impcol_e.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lop163.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/celegans_metabolic.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lund_a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mesh2e1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lund_b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mesh2em5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S10PI_n1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M10PI_n1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/pde225.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rajat14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_183_6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_183_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/plskz362.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_183_4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_183_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ck104.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/gre_512.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Trefethen_300.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/jazz.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M10PI_n.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S10PI_n.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/west0497.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nos6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mhdb416.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/662_bus.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bfwb398.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nnc261.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/tols90.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/west0479.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/arc130.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/USAir97.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M20PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S20PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rw496.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_56.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_54.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_57.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_51.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_50.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_52.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_53.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_55.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_48.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_49.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_47.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_46.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_45.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_43.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_42.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_dcop_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S20PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M20PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/west0381.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/str_0.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/olm500.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/oscil_trans_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/685_bus.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/sherman1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/saylr3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdb450l.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nos7.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdb450.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/tols340.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ww_36_pmec_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bp_0.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S20PI_n1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M20PI_n1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/netscience.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nos2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/str_200.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nos5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/qh768.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/str_400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cz148.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/west0655.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S20PI_n.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M20PI_n.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/str_600.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/G19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bp_200.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/1138_bus.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/G21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/G20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/G18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/G32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/G33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/G34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Trefethen_500.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/gr_30_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bp_400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mcca.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bp_600.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/qh882.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/young3c.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/filter2D_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lns_511.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/west0989.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/steam1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lnsp_511.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bp_800.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_680_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/b2_ss.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/tols1090.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bp_1000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Journals.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bp_1200.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_680_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ck400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bp_1400.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_680_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bp_1600.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bfwa398.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/dw256A.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/dwa512.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/jpwh_991.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S40PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M40PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/dw256B.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/dwb512.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S40PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M40PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/poisson2D.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdb800l.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Chebyshev1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/sherman4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Trefethen_700.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/olm1000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bfwb782.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nnc666.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/pores_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/problem1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cdde4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M40PI_n1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S40PI_n1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cdde3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/tub1000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cdde6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cdde2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdb968.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cdde1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cdde5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cage7.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M40PI_n.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S40PI_n.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/tols2000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/gre_1107.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/utm300.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Chem97ZtZ.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/b_dyn.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/laser.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/west1505.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/plat362.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cz308.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/orsirr_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rajat19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hor_131.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/qh1484.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/pde900.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_541_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_541_4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/poli.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ck656.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_541_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdb1250l.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/iprob.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/orsirr_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdb1250.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_541_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/SciMet.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S80PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M80PI_n1_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/west2021.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S80PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M80PI_n_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/circuit204.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/CAG_mat364.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2dal_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2dal_bci_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2dal_e.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bfwa782.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/plsk1919.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mahindas.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/tols4000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_760_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_760_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/olm2000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/S80PI_n1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/M80PI_n1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fs_760_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rail_1357_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_51.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_47.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_45.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_43.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_48.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_46.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_42.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_49.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_50.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rail_1357.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rajat04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_dcop_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nos3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nnc1374.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mhda416.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cz628.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/zenios.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Pd.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdb2048.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/steam2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rotor2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rbsa480.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rbsb480.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdb2048_noL.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bwm2000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/filter2D.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_43.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/m3plates.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_trans_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fpga_trans_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/pores_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/plbuckle_G.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/polblogs.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lung1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rajat12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/epb0.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/watt_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/saylr4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/watt_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/orsreg_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Trefethen_2000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Si2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/dw1024.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/dw2048.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/spiral.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mhd3200b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cage8.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Alemdar.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/PGPgiantcompo.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdb3200l.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/flowmeter0_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/flowmeter5_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/pde2961.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/init_adder1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/DK01R.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_46.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_49.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_50.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_57.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_56.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_51.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_53.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_61.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_65.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_58.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_69.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_43.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_62.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_63.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_52.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_59.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_48.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_60.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_47.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_68.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_66.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_45.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_67.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_64.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_55.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_42.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_dcop_54.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/radfr1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_42.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/extr1b_A_29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/TSOPF_FS_b9_c1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cryg2500.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cz1268.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/msc01050.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/wang1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/wang2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/olm5000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/shyy41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/sherman3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/meg4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_trans_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/adder_trans_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/add20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/sherman5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/qpband.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/msc00726.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mhd4800b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/swang2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/plbuckle.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/swang1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/coater1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Sieber.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/sherman2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_47.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_75.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_64.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_53.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_71.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_60.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_50.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_63.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_56.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_70.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_59.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_74.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_46.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_55.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_49.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_62.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_69.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_67.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_58.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_52.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_43.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_66.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_73.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lhr01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/tuma2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/poli_large.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/eurqsa.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/g7jac010sc.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bloweybq.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/g7jac010.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cell2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Hamrle2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Lederberg.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdb5000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mcfe.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/circuit_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/plat1919.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/shermanACa.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nopoly.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nasa1824.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/poli3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lns_3937.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lnsp3937.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ncvxqp9.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Chebyshev2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cell1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/sit100.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/msc01440.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/utm1700b.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rail_5177_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/add32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rail_5177.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/n3c6-b7.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2dal_a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2dal.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2dal_bci.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Zewail.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t3dl_e.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_45.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_42.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_54.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_48.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_51.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_65.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_57.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_68.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_61.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_72.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ncvxqp1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/gemat12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fv3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/gemat11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_76.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/jan99jac020sc.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/jan99jac020.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/hydr1c_A_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cz2548.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fv1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/fv2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lhr02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/tomography.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex10hs.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rajat03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/tuma1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstm39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rajat13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nasa2146.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bips98_606.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bcsstk13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/poli4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/pesa.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/viscoplastic1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bips98_1142.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/viscoplastic1_C_6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/sts4098.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/g7jac020sc.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/dw4096.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/dw8192.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/g7jac020.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Chebyshev3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/shermanACd.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/c-44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/flowmeter0.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cage9.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/viscoplastic1_C_7.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/nopss_11k.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bips98_1450.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/viscoplastic1_C_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/utm3060.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/circuit_3.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/big.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/viscoplastic1_C_4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/viscoplastic1_C_1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/xingo_afonso_itaipu.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mimo46x46_system.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/viscoplastic1_C_2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ww_vref_6405.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mimo28x28_system.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/zeros_nopss_13k.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mimo8x8_system.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/TS.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bips07_1693.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/msc04515.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/viscoplastic1_C_5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mark3jac020sc.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mark3jac020.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/Kaufhold.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex7.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/TSOPF_RS_b9_c6.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex9.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cryg10000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cz5108.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/LFAT5000_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/LFAT5000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdist2.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/jan99jac040sc.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/jan99jac040.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/linverse.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdist3a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/LFAT5000_M.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/garon1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bips07_1998.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/powersim.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/LF10000.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/LF10000_E.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bips07_2476.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/mhd3200a.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/descriptor_xingo6u.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/xingo3012.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/bips07_3078.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/orani678.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/thermal.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/flowmeter5.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/LF10000_M.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lhr04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/lhr04c.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/cavity10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/utm5940.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rdist1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_05.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_06.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_04.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_09.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_07.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_10.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_08.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_03.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_02.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_12.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_18.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_19.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_17.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_16.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_13.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_15.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_11.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_14.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_26.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_25.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_21.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_28.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_23.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_24.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_20.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_22.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_38.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_30.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_45.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_45.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_42.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_42.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_43.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_43.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_40.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_39.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_41.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_29.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_33.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_44.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_36.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_32.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_34.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_35.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_37.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4_A_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9_A_01.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q4.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/t2d_q9.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex8.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/comsol.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/epb1.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/ex31.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/rajat27.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/memplus.mtx
./properties -f /home/javed/Desktop/matrix_properties/matrices/spiral_E.mtx

exit 0
